language: node_js
node_js:
  - 6.3.0
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only: master
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - karma start --single-run
